# Generated by Django 4.1.4 on 2023-02-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionErrorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestioningInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastQuestionID', models.IntegerField()),
                ('LastErrorQuestionID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsBank',
            fields=[
                ('QuestionId', models.IntegerField(primary_key=True, serialize=False)),
                ('QuestionContent', models.TextField()),
                ('QuestionAnswer', models.CharField(max_length=1)),
                ('QuestionFlagged', models.BooleanField()),
                ('QuestionCorrected', models.IntegerField()),
                ('QuestionInCorrected', models.IntegerField()),
            ],
        ),
    ]
