# Generated by Django 4.1.4 on 2023-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioninginfo',
            old_name='LastErrorQuestionID',
            new_name='ConfigId',
        ),
        migrations.RenameField(
            model_name='questioninginfo',
            old_name='LastQuestionID',
            new_name='ConfigValue',
        ),
        migrations.AddField(
            model_name='questioninginfo',
            name='ConfigName',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
