# Generated by Django 4.1.4 on 2023-02-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0003_alter_questioninginfo_configname'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionerrorinfo',
            name='ErrorQuestionId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
