# Generated by Django 4.1.4 on 2023-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0004_questionerrorinfo_errorquestionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsbank',
            name='QuestionAnswer',
            field=models.CharField(max_length=2),
        ),
    ]
