# Generated by Django 4.1.4 on 2023-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0005_alter_questionsbank_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsbank',
            name='QuestionComments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
